const demos = [
  'basic/grid1',
  'basic/grid2',
  'basic/grid3',
  'basic/grid4',
  'basic/grid5',
  'basic/grid6',
  'basic/icon',
  'plugins/timeline1',
  'plugins/timeline2',
  'basic/extend1',
  'basic/extend2',
  'basic/button1',
  'basic/button2',
  'form/input1',
  'form/input2',
  'form/input3',
  'form/input4',
  'form/input5',
  'form/input6',
  'dataplugins/autocomplete1',
  'dataplugins/autocomplete2',
  'dataplugins/autocomplete3',
  'dataplugins/autocomplete4',
  'dataplugins/autocomplete5',
  'dataplugins/autocomplete6',
  'dataplugins/autocomplete7',
  'dataplugins/autocomplete8',
  'dataplugins/autocomplete9',
  'dataplugins/autocomplete10',
  'dataplugins/autocomplete11',
  'dataplugins/autocomplete12',
  'dataplugins/autocomplete13',
  'dataplugins/taginput1',
  'dataplugins/taginput2',
  'form/radio1',
  'form/radio2',
  'form/radio3',
  'form/radio4',
  'form/switch1',
  'form/switch2',
  'form/switch3',
  'form/switchlist1',
  'form/switchlist2',
  'form/switchlist3',
  'form/switchlist4',
  'form/checkbox1',
  'form/checkbox2',
  'form/checkbox3',
  'form/checkbox4',
  'form/rate1',
  'form/rate2',
  'form/form1',
  'form/form2',
  'form/form3',
  'form/form4',
  'form/form5',
  'form/form6',
  'dataplugins/datepicker1',
  'dataplugins/datepicker2',
  'dataplugins/datepicker3',
  'dataplugins/datepicker4',
  'dataplugins/datepicker5',
  'dataplugins/datepicker6',
  'dataplugins/datepicker7',
  'dataplugins/datepicker8',
  'dataplugins/daterangepicker1',
  'dataplugins/daterangepicker2',
  'dataplugins/daterangepicker3',
  'dataplugins/daterangepicker4',
  'dataplugins/daterangepicker5',
  'dataplugins/daterangepicker6',
  'dataplugins/datetimepicker1',
  'dataplugins/datetimepicker2',
  'dataplugins/datetimepicker3',
  'dataplugins/datetimepicker4',
  'dataplugins/datetimepicker5',
  'dataplugins/datetimepicker6',
  'dataplugins/datetimepicker7',
  'dataplugins/datetimepicker8',
  'dataplugins/datetimepicker9',
  'dataplugins/select1',
  'dataplugins/select2',
  'dataplugins/select3',
  'dataplugins/select4',
  'dataplugins/select5',
  'dataplugins/select6',
  'dataplugins/select7',
  'dataplugins/select8',
  'dataplugins/select9',
  'dataplugins/select10',
  'dataplugins/select11',
  'dataplugins/select12',
  'dataplugins/timepicker1',
  'dataplugins/timepicker2',
  'dataplugins/timepicker3',
  'dataview/loading1',
  'dataview/loading2',
  'dataview/pagination1',
  'dataview/pagination2',
  'dataview/pagination3',
  'dataview/pagination4',
  'dataview/pagination5',
  'dataview/pagination6',
  'view/badge1',
  'view/badge2',
  'view/badge3',
  'view/badge4',
  'view/badge5',
  'message/message1',
  'message/message2',
  'message/message3',
  'message/message4',
  'message/message5',
  'message/message6',
  'message/modal1',
  'message/modal2',
  'message/modal3',
  'message/modal4',
  'message/modal5',
  'message/modal6',
  'message/modal7',
  'message/modal8',
  'message/modal9',
  'message/modal10',
  'message/modalTest',
  'message/notice1',
  'message/notice2',
  'message/notice3',
  'message/notice4',
  'message/notice5',
  'message/notice6',
  'message/tooltip1',
  'message/tooltip2',
  'message/tooltip3',
  'message/tooltip4',
  'message/tooltip5',
  'view/timeline1',
  'view/timeline2',
]

const components = {};

for (let d of demos) {
  components[d] = () =>
    import (`./${d}`)
}

export default components

// export default {
//     'basic/grid1': resolve => require(['./basic/grid1'], resolve),
//     'basic/grid4': r => require.ensure(['./basic/grid4'], () => r(), 'test'),
//     'basic/grid5': r => require.ensure([], () => r(require('./basic/grid5')), 'test'),
//     'basic/grid6': r => require.ensure([], () => r(require('./basic/grid6')), 'test'),
//     'basic/icon': r => require.ensure([], () => r(require('./basic/icon')), 'test')
//         // 'basic/icon': resolve => require(['./basic/icon'], resolve),
// }

// export default {
//     'basic/grid1': r => require.ensure([], () => r(require('./basic/grid1.vue')), 'basic'),
//     'basic/grid2': r => require.ensure([], () => r(require('./basic/grid2.vue')), 'basic'),
//     'basic/grid3': r => require.ensure([], () => r(require('./basic/grid3.vue')), 'basic'),
//     'basic/grid4': r => require.ensure([], () => r(require('./basic/grid4.vue')), 'basic'),
//     'basic/grid5': r => require.ensure([], () => r(require('./basic/grid5.vue')), 'basic'),
//     'basic/grid6': r => require.ensure([], () => r(require('./basic/grid6.vue')), 'basic'),
//     'basic/icon': r => require.ensure([], () => r(require('./basic/icon.vue')), 'basic'),
//     'basic/extend1': r => require.ensure([], () => r(require('./basic/extend1.vue')), 'basic'),
//     'basic/extend2': r => require.ensure([], () => r(require('./basic/extend2.vue')), 'basic'),
//     'basic/button1': r => require.ensure([], () => r(require('./basic/button1.vue')), 'basic'),
//     'basic/button2': r => require.ensure([], () => r(require('./basic/button2.vue')), 'basic'),
//     'form/input1': r => require.ensure([], () => r(require('./form/input1.vue')), 'form'),
//     'form/input2': r => require.ensure([], () => r(require('./form/input2.vue')), 'form'),
//     'form/input3': r => require.ensure([], () => r(require('./form/input3.vue')), 'form'),
//     'form/input4': r => require.ensure([], () => r(require('./form/input4.vue')), 'form'),
//     'form/input5': r => require.ensure([], () => r(require('./form/input5.vue')), 'form'),
//     'form/input6': r => require.ensure([], () => r(require('./form/input6.vue')), 'form'),
//     'form/radio1': r => require.ensure([], () => r(require('./form/radio1.vue')), 'form'),
//     'form/radio2': r => require.ensure([], () => r(require('./form/radio2.vue')), 'form'),
//     'form/radio3': r => require.ensure([], () => r(require('./form/radio3.vue')), 'form'),
//     'form/radio4': r => require.ensure([], () => r(require('./form/radio4.vue')), 'form'),
//     'form/switch1': r => require.ensure([], () => r(require('./form/switch1.vue')), 'form'),
//     'form/switch2': r => require.ensure([], () => r(require('./form/switch2.vue')), 'form'),
//     'form/switch3': r => require.ensure([], () => r(require('./form/switch3.vue')), 'form'),
//     'form/switchlist1': r => require.ensure([], () => r(require('./form/switchlist1.vue')), 'form'),
//     'form/switchlist2': r => require.ensure([], () => r(require('./form/switchlist2.vue')), 'form'),
//     'form/switchlist3': r => require.ensure([], () => r(require('./form/switchlist3.vue')), 'form'),
//     'form/switchlist4': r => require.ensure([], () => r(require('./form/switchlist4.vue')), 'form'),
//     'form/checkbox1': r => require.ensure([], () => r(require('./form/checkbox1.vue')), 'form'),
//     'form/checkbox2': r => require.ensure([], () => r(require('./form/checkbox2.vue')), 'form'),
//     'form/checkbox3': r => require.ensure([], () => r(require('./form/checkbox3.vue')), 'form'),
//     'form/checkbox4': r => require.ensure([], () => r(require('./form/checkbox4.vue')), 'form'),
//     'form/rate1': r => require.ensure([], () => r(require('./form/rate1.vue')), 'form'),
//     'form/rate2': r => require.ensure([], () => r(require('./form/rate2.vue')), 'form'),
//     'form/form1': r => require.ensure([], () => r(require('./form/form1.vue')), 'form'),
//     'form/form2': r => require.ensure([], () => r(require('./form/form2.vue')), 'form'),
//     'form/form3': r => require.ensure([], () => r(require('./form/form3.vue')), 'form'),
//     'form/form4': r => require.ensure([], () => r(require('./form/form4.vue')), 'form'),
//     'form/form5': r => require.ensure([], () => r(require('./form/form5.vue')), 'form'),
//     'form/form6': r => require.ensure([], () => r(require('./form/form6.vue')), 'form'),
//     'dataplugins/datepicker1': r => require.ensure([], () => r(require('./dataplugins/datepicker1.vue')), 'dataplugins'),
//     'dataplugins/datepicker2': r => require.ensure([], () => r(require('./dataplugins/datepicker2.vue')), 'dataplugins'),
//     'dataplugins/datepicker3': r => require.ensure([], () => r(require('./dataplugins/datepicker3.vue')), 'dataplugins'),
//     'dataplugins/datepicker4': r => require.ensure([], () => r(require('./dataplugins/datepicker4.vue')), 'dataplugins'),
//     'dataplugins/datepicker5': r => require.ensure([], () => r(require('./dataplugins/datepicker5.vue')), 'dataplugins'),
//     'dataplugins/datepicker6': r => require.ensure([], () => r(require('./dataplugins/datepicker6.vue')), 'dataplugins'),
//     'dataplugins/datepicker7': r => require.ensure([], () => r(require('./dataplugins/datepicker7.vue')), 'dataplugins'),
//     'dataplugins/datepicker8': r => require.ensure([], () => r(require('./dataplugins/datepicker8.vue')), 'dataplugins'),
//     'dataplugins/daterangepicker1': r => require.ensure([], () => r(require('./dataplugins/daterangepicker1.vue')), 'dataplugins'),
//     'dataplugins/daterangepicker2': r => require.ensure([], () => r(require('./dataplugins/daterangepicker2.vue')), 'dataplugins'),
//     'dataplugins/daterangepicker3': r => require.ensure([], () => r(require('./dataplugins/daterangepicker3.vue')), 'dataplugins'),
//     'dataplugins/daterangepicker4': r => require.ensure([], () => r(require('./dataplugins/daterangepicker4.vue')), 'dataplugins'),
//     'dataplugins/daterangepicker5': r => require.ensure([], () => r(require('./dataplugins/daterangepicker5.vue')), 'dataplugins'),
//     'dataplugins/daterangepicker6': r => require.ensure([], () => r(require('./dataplugins/daterangepicker6.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker1': r => require.ensure([], () => r(require('./dataplugins/datetimepicker1.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker2': r => require.ensure([], () => r(require('./dataplugins/datetimepicker2.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker3': r => require.ensure([], () => r(require('./dataplugins/datetimepicker3.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker4': r => require.ensure([], () => r(require('./dataplugins/datetimepicker4.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker5': r => require.ensure([], () => r(require('./dataplugins/datetimepicker5.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker6': r => require.ensure([], () => r(require('./dataplugins/datetimepicker6.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker7': r => require.ensure([], () => r(require('./dataplugins/datetimepicker7.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker8': r => require.ensure([], () => r(require('./dataplugins/datetimepicker8.vue')), 'dataplugins'),
//     'dataplugins/datetimepicker9': r => require.ensure([], () => r(require('./dataplugins/datetimepicker9.vue')), 'dataplugins'),
//     'dataplugins/select1': r => require.ensure([], () => r(require('./dataplugins/select1.vue')), 'dataplugins'),
//     'dataplugins/select2': r => require.ensure([], () => r(require('./dataplugins/select2.vue')), 'dataplugins'),
//     'dataplugins/select3': r => require.ensure([], () => r(require('./dataplugins/select3.vue')), 'dataplugins'),
//     'dataplugins/select4': r => require.ensure([], () => r(require('./dataplugins/select4.vue')), 'dataplugins'),
//     'dataplugins/select5': r => require.ensure([], () => r(require('./dataplugins/select5.vue')), 'dataplugins'),
//     'dataplugins/select6': r => require.ensure([], () => r(require('./dataplugins/select6.vue')), 'dataplugins'),
//     'dataplugins/select7': r => require.ensure([], () => r(require('./dataplugins/select7.vue')), 'dataplugins'),
//     'dataplugins/select8': r => require.ensure([], () => r(require('./dataplugins/select8.vue')), 'dataplugins'),
//     'dataplugins/select9': r => require.ensure([], () => r(require('./dataplugins/select9.vue')), 'dataplugins'),
//     'dataplugins/select10': r => require.ensure([], () => r(require('./dataplugins/select10.vue')), 'dataplugins'),
//     'dataplugins/select11': r => require.ensure([], () => r(require('./dataplugins/select11.vue')), 'dataplugins'),
//     'dataplugins/select12': r => require.ensure([], () => r(require('./dataplugins/select12.vue')), 'dataplugins'),
//     'dataplugins/timepicker1': r => require.ensure([], () => r(require('./dataplugins/timepicker1.vue')), 'dataplugins'),
//     'dataplugins/timepicker2': r => require.ensure([], () => r(require('./dataplugins/timepicker2.vue')), 'dataplugins'),
//     'dataplugins/timepicker3': r => require.ensure([], () => r(require('./dataplugins/timepicker3.vue')), 'dataplugins'),
//     'dataview/loading1': r => require.ensure([], () => r(require('./dataview/loading1.vue')), 'dataview'),
//     'dataview/loading2': r => require.ensure([], () => r(require('./dataview/loading2.vue')), 'dataview'),
//     'dataview/pagination1': r => require.ensure([], () => r(require('./dataview/pagination1.vue')), 'dataview'),
//     'dataview/pagination2': r => require.ensure([], () => r(require('./dataview/pagination2.vue')), 'dataview'),
//     'dataview/pagination3': r => require.ensure([], () => r(require('./dataview/pagination3.vue')), 'dataview'),
//     'dataview/pagination4': r => require.ensure([], () => r(require('./dataview/pagination4.vue')), 'dataview'),
//     'dataview/pagination5': r => require.ensure([], () => r(require('./dataview/pagination5.vue')), 'dataview'),
//     'dataview/pagination6': r => require.ensure([], () => r(require('./dataview/pagination6.vue')), 'dataview'),
//     'message/message1': r => require.ensure([], () => r(require('./message/message1.vue')), 'message'),
//     'message/message2': r => require.ensure([], () => r(require('./message/message2.vue')), 'message'),
//     'message/message3': r => require.ensure([], () => r(require('./message/message3.vue')), 'message'),
//     'message/message4': r => require.ensure([], () => r(require('./message/message4.vue')), 'message'),
//     'message/message5': r => require.ensure([], () => r(require('./message/message5.vue')), 'message'),
//     'message/message6': r => require.ensure([], () => r(require('./message/message6.vue')), 'message'),
//     'message/modal1': r => require.ensure([], () => r(require('./message/modal1.vue')), 'message'),
//     'message/modal2': r => require.ensure([], () => r(require('./message/modal2.vue')), 'message'),
//     'message/modal3': r => require.ensure([], () => r(require('./message/modal3.vue')), 'message'),
//     'message/modal4': r => require.ensure([], () => r(require('./message/modal4.vue')), 'message'),
//     'message/modal5': r => require.ensure([], () => r(require('./message/modal5.vue')), 'message'),
//     'message/modal6': r => require.ensure([], () => r(require('./message/modal6.vue')), 'message'),
//     'message/modal7': r => require.ensure([], () => r(require('./message/modal7.vue')), 'message'),
//     'message/modal8': r => require.ensure([], () => r(require('./message/modal8.vue')), 'message'),
//     'message/modal9': r => require.ensure([], () => r(require('./message/modal9.vue')), 'message'),
//     'message/modal10': r => require.ensure([], () => r(require('./message/modal10.vue')), 'message'),
//     'message/modalTest': r => require.ensure([], () => r(require('./message/modalTest.vue')), 'message'),
//     'message/notice1': r => require.ensure([], () => r(require('./message/notice1.vue')), 'message'),
//     'message/notice2': r => require.ensure([], () => r(require('./message/notice2.vue')), 'message'),
//     'message/notice3': r => require.ensure([], () => r(require('./message/notice3.vue')), 'message'),
//     'message/notice4': r => require.ensure([], () => r(require('./message/notice4.vue')), 'message'),
//     'message/notice5': r => require.ensure([], () => r(require('./message/notice5.vue')), 'message'),
//     'message/notice6': r => require.ensure([], () => r(require('./message/notice6.vue')), 'message'),
//     'message/tooltip1': r => require.ensure([], () => r(require('./message/tooltip1.vue')), 'message'),
//     'message/tooltip2': r => require.ensure([], () => r(require('./message/tooltip2.vue')), 'message'),
//     'message/tooltip3': r => require.ensure([], () => r(require('./message/tooltip3.vue')), 'message'),
//     'message/tooltip4': r => require.ensure([], () => r(require('./message/tooltip4.vue')), 'message'),
//     'message/tooltip5': r => require.ensure([], () => r(require('./message/tooltip5.vue')), 'message'),
//     'view/timeline1': r => require.ensure([], () => r(require('./view/timeline1.vue')), 'view'),
//     'view/timeline2': r => require.ensure([], () => r(require('./view/timeline2.vue')), 'view')
// }