// const demos = [
//   'basic/grid1',
//   'basic/grid2',
//   'basic/grid3',
//   'basic/grid4',
//   'basic/grid5',
//   'basic/grid6',
//   'basic/icon',
//   'plugins/timeline1',
//   'plugins/timeline2',
//   'basic/extend1',
//   'basic/extend2',
//   'basic/button1',
//   'basic/button2',
//   'form/input1',
//   'form/input2',
//   'form/input3',
//   'form/input4',
//   'form/input5',
//   'form/input6',
//   'dataplugins/autocomplete1',
//   'dataplugins/autocomplete2',
//   'dataplugins/autocomplete3',
//   'dataplugins/autocomplete4',
//   'dataplugins/autocomplete5',
//   'dataplugins/autocomplete6',
//   'dataplugins/autocomplete7',
//   'dataplugins/autocomplete8',
//   'dataplugins/autocomplete9',
//   'dataplugins/autocomplete10',
//   'dataplugins/autocomplete11',
//   'dataplugins/autocomplete12',
//   'dataplugins/autocomplete13',
//   'dataplugins/taginput1',
//   'dataplugins/taginput2',
//   'form/radio1',
//   'form/radio2',
//   'form/radio3',
//   'form/radio4',
//   'form/switch1',
//   'form/switch2',
//   'form/switch3',
//   'form/switchlist1',
//   'form/switchlist2',
//   'form/switchlist3',
//   'form/switchlist4',
//   'form/checkbox1',
//   'form/checkbox2',
//   'form/checkbox3',
//   'form/checkbox4',
//   'form/rate1',
//   'form/rate2',
//   'form/form1',
//   'form/form2',
//   'form/form3',
//   'form/form4',
//   'form/form5',
//   'form/form6',
//   'dataplugins/datepicker1',
//   'dataplugins/datepicker2',
//   'dataplugins/datepicker3',
//   'dataplugins/datepicker4',
//   'dataplugins/datepicker5',
//   'dataplugins/datepicker6',
//   'dataplugins/datepicker7',
//   'dataplugins/datepicker8',
//   'dataplugins/daterangepicker1',
//   'dataplugins/daterangepicker2',
//   'dataplugins/daterangepicker3',
//   'dataplugins/daterangepicker4',
//   'dataplugins/daterangepicker5',
//   'dataplugins/daterangepicker6',
//   'dataplugins/datetimepicker1',
//   'dataplugins/datetimepicker2',
//   'dataplugins/datetimepicker3',
//   'dataplugins/datetimepicker4',
//   'dataplugins/datetimepicker5',
//   'dataplugins/datetimepicker6',
//   'dataplugins/datetimepicker7',
//   'dataplugins/datetimepicker8',
//   'dataplugins/datetimepicker9',
//   'dataplugins/select1',
//   'dataplugins/select2',
//   'dataplugins/select3',
//   'dataplugins/select4',
//   'dataplugins/select5',
//   'dataplugins/select6',
//   'dataplugins/select7',
//   'dataplugins/select8',
//   'dataplugins/select9',
//   'dataplugins/select10',
//   'dataplugins/select11',
//   'dataplugins/select12',
//   'dataplugins/timepicker1',
//   'dataplugins/timepicker2',
//   'dataplugins/timepicker3',
//   'dataview/loading1',
//   'dataview/loading2',
//   'dataview/pagination1',
//   'dataview/pagination2',
//   'dataview/pagination3',
//   'dataview/pagination4',
//   'dataview/pagination5',
//   'dataview/pagination6',
//   'view/badge1',
//   'view/badge2',
//   'view/badge3',
//   'view/badge4',
//   'view/badge5',
//   'message/message1',
//   'message/message2',
//   'message/message3',
//   'message/message4',
//   'message/message5',
//   'message/message6',
//   'message/modal1',
//   'message/modal2',
//   'message/modal3',
//   'message/modal4',
//   'message/modal5',
//   'message/modal6',
//   'message/modal7',
//   'message/modal8',
//   'message/modal9',
//   'message/modal10',
//   'message/modalTest',
//   'message/notice1',
//   'message/notice2',
//   'message/notice3',
//   'message/notice4',
//   'message/notice5',
//   'message/notice6',
//   'message/tooltip1',
//   'message/tooltip2',
//   'message/tooltip3',
//   'message/tooltip4',
//   'message/tooltip5',
//   'view/timeline1',
//   'view/timeline2',
// ]

// const components = {};

// for (let d of demos) {
//   components[d] = () =>
//     import (`./${d}`)
// }

// export default components

// export default {
//     'basic/grid1': resolve => require(['./basic/grid1'])),
//     'basic/grid4': resolve => require.ensure(['./basic/grid4'], () => r(), 'test'),
//     'basic/grid5': resolve => require.ensure([], require => require('./basic/grid5')),'test'),
//     'basic/grid6': resolve => require.ensure([], require => require('./basic/grid6')),'test'),
//     'basic/icon': resolve => require.ensure([], require => require('./basic/icon')),'test')
//         // 'basic/icon': resolve => require(['./basic/icon'])),
// }

export default {
  'basic/grid1': function (resolve) { require.ensure([], function (require) { resolve(require('./basic/grid1.vue')) }, 'basic') },
  'basic/grid2': function (resolve) { require.ensure([], function (require) { resolve(require('./basic/grid2.vue')) }, 'basic') },
  'basic/grid3': function (resolve) { require.ensure([], function (require) { resolve(require('./basic/grid3.vue')) }, 'basic') },
  'basic/grid4': function (resolve) { require.ensure([], function (require) { resolve(require('./basic/grid4.vue')) }, 'basic') },
  'basic/grid5': function (resolve) { require.ensure([], function (require) { resolve(require('./basic/grid5.vue')) }, 'basic') },
  'basic/grid6': function (resolve) { require.ensure([], function (require) { resolve(require('./basic/grid6.vue')) }, 'basic') },
  'basic/icon': function (resolve) { require.ensure([], function (require) { resolve(require('./basic/icon.vue')) }, 'basic') },
  'basic/extend1': resolve => require.ensure([], require => require('./basic/extend1.vue'), 'basic'),
  'basic/extend2': resolve => require.ensure([], require => require('./basic/extend2.vue'), 'basic'),
  'basic/button1': resolve => require.ensure([], require => require('./basic/button1.vue'), 'basic'),
  'basic/button2': resolve => require.ensure([], require => require('./basic/button2.vue'), 'basic'),
  'form/input1': resolve => require.ensure([], require => require('./form/input1.vue'), 'form'),
  'form/input2': resolve => require.ensure([], require => require('./form/input2.vue'), 'form'),
  'form/input3': resolve => require.ensure([], require => require('./form/input3.vue'), 'form'),
  'form/input4': resolve => require.ensure([], require => require('./form/input4.vue'), 'form'),
  'form/input5': resolve => require.ensure([], require => require('./form/input5.vue'), 'form'),
  'form/input6': resolve => require.ensure([], require => require('./form/input6.vue'), 'form'),
  'form/radio1': resolve => require.ensure([], require => require('./form/radio1.vue'), 'form'),
  'form/radio2': resolve => require.ensure([], require => require('./form/radio2.vue'), 'form'),
  'form/radio3': resolve => require.ensure([], require => require('./form/radio3.vue'), 'form'),
  'form/radio4': resolve => require.ensure([], require => require('./form/radio4.vue'), 'form'),
  'form/switch1': resolve => require.ensure([], require => require('./form/switch1.vue'), 'form'),
  'form/switch2': resolve => require.ensure([], require => require('./form/switch2.vue'), 'form'),
  'form/switch3': resolve => require.ensure([], require => require('./form/switch3.vue'), 'form'),
  'form/switchlist1': resolve => require.ensure([], require => require('./form/switchlist1.vue'), 'form'),
  'form/switchlist2': resolve => require.ensure([], require => require('./form/switchlist2.vue'), 'form'),
  'form/switchlist3': resolve => require.ensure([], require => require('./form/switchlist3.vue'), 'form'),
  'form/switchlist4': resolve => require.ensure([], require => require('./form/switchlist4.vue'), 'form'),
  'form/checkbox1': resolve => require.ensure([], require => require('./form/checkbox1.vue'), 'form'),
  'form/checkbox2': resolve => require.ensure([], require => require('./form/checkbox2.vue'), 'form'),
  'form/checkbox3': resolve => require.ensure([], require => require('./form/checkbox3.vue'), 'form'),
  'form/checkbox4': resolve => require.ensure([], require => require('./form/checkbox4.vue'), 'form'),
  'form/rate1': resolve => require.ensure([], require => require('./form/rate1.vue'), 'form'),
  'form/rate2': resolve => require.ensure([], require => require('./form/rate2.vue'), 'form'),
  'form/form1': resolve => require.ensure([], require => require('./form/form1.vue'), 'form'),
  'form/form2': resolve => require.ensure([], require => require('./form/form2.vue'), 'form'),
  'form/form3': resolve => require.ensure([], require => require('./form/form3.vue'), 'form'),
  'form/form4': resolve => require.ensure([], require => require('./form/form4.vue'), 'form'),
  'form/form5': resolve => require.ensure([], require => require('./form/form5.vue'), 'form'),
  'form/form6': resolve => require.ensure([], require => require('./form/form6.vue'), 'form'),
  'dataplugins/datepicker1': resolve => require.ensure([], require => require('./dataplugins/datepicker1.vue'), 'dataplugins'),
  'dataplugins/datepicker2': resolve => require.ensure([], require => require('./dataplugins/datepicker2.vue'), 'dataplugins'),
  'dataplugins/datepicker3': resolve => require.ensure([], require => require('./dataplugins/datepicker3.vue'), 'dataplugins'),
  'dataplugins/datepicker4': resolve => require.ensure([], require => require('./dataplugins/datepicker4.vue'), 'dataplugins'),
  'dataplugins/datepicker5': resolve => require.ensure([], require => require('./dataplugins/datepicker5.vue'), 'dataplugins'),
  'dataplugins/datepicker6': resolve => require.ensure([], require => require('./dataplugins/datepicker6.vue'), 'dataplugins'),
  'dataplugins/datepicker7': resolve => require.ensure([], require => require('./dataplugins/datepicker7.vue'), 'dataplugins'),
  'dataplugins/datepicker8': resolve => require.ensure([], require => require('./dataplugins/datepicker8.vue'), 'dataplugins'),
  'dataplugins/daterangepicker1': resolve => require.ensure([], require => require('./dataplugins/daterangepicker1.vue'), 'dataplugins'),
  'dataplugins/daterangepicker2': resolve => require.ensure([], require => require('./dataplugins/daterangepicker2.vue'), 'dataplugins'),
  'dataplugins/daterangepicker3': resolve => require.ensure([], require => require('./dataplugins/daterangepicker3.vue'), 'dataplugins'),
  'dataplugins/daterangepicker4': resolve => require.ensure([], require => require('./dataplugins/daterangepicker4.vue'), 'dataplugins'),
  'dataplugins/daterangepicker5': resolve => require.ensure([], require => require('./dataplugins/daterangepicker5.vue'), 'dataplugins'),
  'dataplugins/daterangepicker6': resolve => require.ensure([], require => require('./dataplugins/daterangepicker6.vue'), 'dataplugins'),
  'dataplugins/datetimepicker1': resolve => require.ensure([], require => require('./dataplugins/datetimepicker1.vue'), 'dataplugins'),
  'dataplugins/datetimepicker2': resolve => require.ensure([], require => require('./dataplugins/datetimepicker2.vue'), 'dataplugins'),
  'dataplugins/datetimepicker3': resolve => require.ensure([], require => require('./dataplugins/datetimepicker3.vue'), 'dataplugins'),
  'dataplugins/datetimepicker4': resolve => require.ensure([], require => require('./dataplugins/datetimepicker4.vue'), 'dataplugins'),
  'dataplugins/datetimepicker5': resolve => require.ensure([], require => require('./dataplugins/datetimepicker5.vue'), 'dataplugins'),
  'dataplugins/datetimepicker6': resolve => require.ensure([], require => require('./dataplugins/datetimepicker6.vue'), 'dataplugins'),
  'dataplugins/datetimepicker7': resolve => require.ensure([], require => require('./dataplugins/datetimepicker7.vue'), 'dataplugins'),
  'dataplugins/datetimepicker8': resolve => require.ensure([], require => require('./dataplugins/datetimepicker8.vue'), 'dataplugins'),
  'dataplugins/datetimepicker9': resolve => require.ensure([], require => require('./dataplugins/datetimepicker9.vue'), 'dataplugins'),
  'dataplugins/select1': resolve => require.ensure([], require => require('./dataplugins/select1.vue'), 'dataplugins'),
  'dataplugins/select2': resolve => require.ensure([], require => require('./dataplugins/select2.vue'), 'dataplugins'),
  'dataplugins/select3': resolve => require.ensure([], require => require('./dataplugins/select3.vue'), 'dataplugins'),
  'dataplugins/select4': resolve => require.ensure([], require => require('./dataplugins/select4.vue'), 'dataplugins'),
  'dataplugins/select5': resolve => require.ensure([], require => require('./dataplugins/select5.vue'), 'dataplugins'),
  'dataplugins/select6': resolve => require.ensure([], require => require('./dataplugins/select6.vue'), 'dataplugins'),
  'dataplugins/select7': resolve => require.ensure([], require => require('./dataplugins/select7.vue'), 'dataplugins'),
  'dataplugins/select8': resolve => require.ensure([], require => require('./dataplugins/select8.vue'), 'dataplugins'),
  'dataplugins/select9': resolve => require.ensure([], require => require('./dataplugins/select9.vue'), 'dataplugins'),
  'dataplugins/select10': resolve => require.ensure([], require => require('./dataplugins/select10.vue'), 'dataplugins'),
  'dataplugins/select11': resolve => require.ensure([], require => require('./dataplugins/select11.vue'), 'dataplugins'),
  'dataplugins/select12': resolve => require.ensure([], require => require('./dataplugins/select12.vue'), 'dataplugins'),
  'dataplugins/timepicker1': resolve => require.ensure([], require => require('./dataplugins/timepicker1.vue'), 'dataplugins'),
  'dataplugins/timepicker2': resolve => require.ensure([], require => require('./dataplugins/timepicker2.vue'), 'dataplugins'),
  'dataplugins/timepicker3': resolve => require.ensure([], require => require('./dataplugins/timepicker3.vue'), 'dataplugins'),
  'dataview/loading1': resolve => require.ensure([], require => require('./dataview/loading1.vue'), 'dataview'),
  'dataview/loading2': resolve => require.ensure([], require => require('./dataview/loading2.vue'), 'dataview'),
  'dataview/pagination1': resolve => require.ensure([], require => require('./dataview/pagination1.vue'), 'dataview'),
  'dataview/pagination2': resolve => require.ensure([], require => require('./dataview/pagination2.vue'), 'dataview'),
  'dataview/pagination3': resolve => require.ensure([], require => require('./dataview/pagination3.vue'), 'dataview'),
  'dataview/pagination4': resolve => require.ensure([], require => require('./dataview/pagination4.vue'), 'dataview'),
  'dataview/pagination5': resolve => require.ensure([], require => require('./dataview/pagination5.vue'), 'dataview'),
  'dataview/pagination6': resolve => require.ensure([], require => require('./dataview/pagination6.vue'), 'dataview'),
  'message/message1': resolve => require.ensure([], require => require('./message/message1.vue'), 'message'),
  'message/message2': resolve => require.ensure([], require => require('./message/message2.vue'), 'message'),
  'message/message3': resolve => require.ensure([], require => require('./message/message3.vue'), 'message'),
  'message/message4': resolve => require.ensure([], require => require('./message/message4.vue'), 'message'),
  'message/message5': resolve => require.ensure([], require => require('./message/message5.vue'), 'message'),
  'message/message6': resolve => require.ensure([], require => require('./message/message6.vue'), 'message'),
  'message/modal1': resolve => require.ensure([], require => require('./message/modal1.vue'), 'message'),
  'message/modal2': resolve => require.ensure([], require => require('./message/modal2.vue'), 'message'),
  'message/modal3': resolve => require.ensure([], require => require('./message/modal3.vue'), 'message'),
  'message/modal4': resolve => require.ensure([], require => require('./message/modal4.vue'), 'message'),
  'message/modal5': resolve => require.ensure([], require => require('./message/modal5.vue'), 'message'),
  'message/modal6': resolve => require.ensure([], require => require('./message/modal6.vue'), 'message'),
  'message/modal7': resolve => require.ensure([], require => require('./message/modal7.vue'), 'message'),
  'message/modal8': resolve => require.ensure([], require => require('./message/modal8.vue'), 'message'),
  'message/modal9': resolve => require.ensure([], require => require('./message/modal9.vue'), 'message'),
  'message/modal10': resolve => require.ensure([], require => require('./message/modal10.vue'), 'message'),
  'message/modalTest': resolve => require.ensure([], require => require('./message/modalTest.vue'), 'message'),
  'message/notice1': resolve => require.ensure([], require => require('./message/notice1.vue'), 'message'),
  'message/notice2': resolve => require.ensure([], require => require('./message/notice2.vue'), 'message'),
  'message/notice3': resolve => require.ensure([], require => require('./message/notice3.vue'), 'message'),
  'message/notice4': resolve => require.ensure([], require => require('./message/notice4.vue'), 'message'),
  'message/notice5': resolve => require.ensure([], require => require('./message/notice5.vue'), 'message'),
  'message/notice6': resolve => require.ensure([], require => require('./message/notice6.vue'), 'message'),
  'message/tooltip1': resolve => require.ensure([], require => require('./message/tooltip1.vue'), 'message'),
  'message/tooltip2': resolve => require.ensure([], require => require('./message/tooltip2.vue'), 'message'),
  'message/tooltip3': resolve => require.ensure([], require => require('./message/tooltip3.vue'), 'message'),
  'message/tooltip4': resolve => require.ensure([], require => require('./message/tooltip4.vue'), 'message'),
  'message/tooltip5': resolve => require.ensure([], require => require('./message/tooltip5.vue'), 'message'),
  'view/timeline1': resolve => require.ensure([], require => require('./view/timeline1.vue'), 'view'),
  'view/timeline2': resolve => require.ensure([], require => require('./view/timeline2.vue'), 'view'),
  'dataplugins/autocomplete1': resolve => require.ensure([], require => require('./dataplugins/autocomplete1'), 'plugins'),
  'dataplugins/autocomplete2': resolve => require.ensure([], require => require('./dataplugins/autocomplete2'), 'plugins'),
  'dataplugins/autocomplete3': resolve => require.ensure([], require => require('./dataplugins/autocomplete3'), 'plugins'),
  'dataplugins/autocomplete4': resolve => require.ensure([], require => require('./dataplugins/autocomplete4'), 'plugins'),
  'dataplugins/autocomplete5': resolve => require.ensure([], require => require('./dataplugins/autocomplete5'), 'plugins'),
  'dataplugins/autocomplete6': resolve => require.ensure([], require => require('./dataplugins/autocomplete6'), 'plugins'),
  'dataplugins/autocomplete7': resolve => require.ensure([], require => require('./dataplugins/autocomplete7'), 'plugins'),
  'dataplugins/autocomplete8': resolve => require.ensure([], require => require('./dataplugins/autocomplete8'), 'plugins'),
  'dataplugins/autocomplete9': resolve => require.ensure([], require => require('./dataplugins/autocomplete9'), 'plugins'),
  'dataplugins/autocomplete10': resolve => require.ensure([], require => require('./dataplugins/autocomplete10'), 'plugins'),
  'dataplugins/autocomplete11': resolve => require.ensure([], require => require('./dataplugins/autocomplete11'), 'plugins'),
  'dataplugins/autocomplete12': resolve => require.ensure([], require => require('./dataplugins/autocomplete12'), 'plugins'),
  'dataplugins/autocomplete13': resolve => require.ensure([], require => require('./dataplugins/autocomplete13'), 'plugins'),
  'dataplugins/taginput1': resolve => require.ensure([], require => require('./dataplugins/taginput1'), 'plugins'),
  'dataplugins/taginput2': resolve => require.ensure([], require => require('./dataplugins/taginput2'), 'plugins'),
}
