stages:
- deploy

deploy:
  stage: deploy
  script:
    - bash .gitlab-deploy.sh
  only:
    - master
  tags:
    - heyui
  when: manual

reset:
  stage: deploy
  script:
    - bash .gitlab-reset.sh
  only:
    - master
  tags:
    - heyui
  when: manual

only-deploy-file:
  stage: deploy
  script:
    - bash .gitlab-only-deploy-file.sh
  only:
    - master
  tags:
    - heyui
  when: manual