<template>
  <div>
    <p>选中值：{{select}}</p>
    <div v-width="300"><Select v-model="select" :datas="param" :filterable="true" :multiple="true"></Select></div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      select: '',
      param: [
        'Honolulu 夏威夷檀香山',
        'Anchorage 阿拉斯加安克雷奇',
        'Vancouver 温哥华',
        'San Francisco 旧金山',
        'Seattle 西雅图',
        'Los Angeles 洛杉矶',
        'Aklavik 阿克拉维克',
        'Edmonton 艾德蒙顿',
        'Phoenix 凤凰城',
        'Denver 丹佛',
        'Mexico City 墨西哥城',
        'Winnipeg 温尼伯',
        'Houston 休斯敦',
        'Minneapolis 明尼亚波利斯',
        'St.Paul 圣保罗',
        'New Orleans 新奥尔良',
        'Chicago 芝加哥',
        'Montgomery 蒙哥马利',
        'Guatemala 危地马拉',
        'San Salvador 圣萨尔瓦多',
        'Tegucigalpa 特古西加尔巴',
        'Managua 马那瓜',
        'Havana 哈瓦那',
        'Indianapolis 印地安纳波利斯',
        'Atlanta 亚特兰大',
        'Detroit 底特律',
        'Washington DC 华盛顿哥伦比亚特区',
        'Philadelphia 费城',
        'Toronto 多伦多',
        'Ottawa 渥太华',
        'Nassau 拿骚',
        'Lima 利马',
        'Kingston 金斯敦',
        'Bogota 波哥大',
        'New York 纽约',
        'Montreal 蒙特利尔',
        'Boston 波士顿',
        'Santo Domingo 圣多明各',
        'La Paz 拉帕兹',
        'Caracas 加拉加斯',
        'San Juan 圣胡安',
        'Halifax 哈里法克斯',
        'Santiago 圣地亚哥',
        'Asuncion 亚松森',
        'St.John\'s 圣约翰斯',
        'Buenos Aires 布宜诺斯艾利斯',
        'Montevideo 蒙特维的亚',
        'Brasilia 巴西利亚',
        'Sao Paulo 圣保罗',
        'Rio de Janeiro 里约热内卢',
        'Reykjavik 雷克雅未克',
        'Lisbon 里斯本',
        'Casablanca 卡萨布兰卡',
        'Dublin 都柏林',
        'London 伦敦',
        'Madrid 马德里',
        'Barcelona 巴塞罗那',
        'Paris 巴黎',
        'Lagos 拉各斯',
        'Algiers 阿尔及尔',
        'Brussels 布鲁塞尔',
        'Amsterdam 阿姆斯特丹',
        'Geneva 日内瓦',
        'Zurich 苏黎世',
        'Frankfurt 法兰克福',
        'Oslo 奥斯陆',
        'Copenhagen 哥本哈根',
        'Rome 罗马',
        'Berlin 柏林',
        'Prague 布拉格',
        'Zagreb 萨格雷布',
        'Vienna 维也纳',
        'Stockholm 斯德哥尔摩',
        'Budapest 布达佩斯',
        'Belgrade 贝尔格莱德',
        'Warsaw 华沙',
        'Cape Town 开普敦',
        'Sofia 索非亚',
        'Athens 雅典城',
        'Tallinn 塔林',
        'Helsinki 赫尔辛基',
        'Bucharest 布加勒斯特',
        'Minsk 明斯克',
        'Johannesburg 约翰尼斯堡'
      ]
    };
  }
};
</script>
