const titles = {
  'basicGrid': 'Grid 布局',
  'basicColor': 'Color 色彩',
  'basicIcon': 'Icon 图标',
  'basicExtend': 'Extend 扩展',
  'basicButton': 'Button 按钮',
  'formInput': 'Input 输入框',
  'formTextarea': 'Textarea 文本框',
  'formRadio': 'Radio 单选',
  'formSwitchlist': 'SwitchList 选项切换',
  'formSwitch': 'Switch 开关',
  'formCheckbox': 'Checkbox 多选',
  'formSlider': 'Slider 滑块',
  'formRate': 'Rate 评分',
  'formForm': 'Form 表单',
  'pluginSelect': 'Select 下拉选择',
  'pluginAuto': 'AutoPicker 自动补全',
  'pluginDate': 'DatePicker 日期选择',
  'pluginCity': 'CityPicker 城市选择',
  'dataPluginTree': 'TreePicker 树选择',
  'pluginTaginput': 'TagInput 标签',
  'pluginUpload': 'Upload 上传',
  'pluginValid': 'Valid 数据验证',
  'viewSearchinput': 'SearchInput 搜索框',
  'viewTable': 'Table 表格',
  'viewPage': 'Pagination 分页',
  'viewSpin': 'Spin 加载中',
  'viewTag': 'Tag 标签',
  'viewProgress': 'Progress 进度条',
  'viewCircle': 'Circle 进度环',
  'pluginTree': 'Tree 树',
  'pluginDialog': 'Dialog 弹框',
  'pluginDropdown': 'Dropdown 原生下拉控件',
  'pluginDropdownmenu': 'DropdownMenu 下拉菜单',
  'pluginLoadingbar': 'LoadingBar 加载进度条',
  'messageTip': 'Message 提示',
  'messageNotice': 'Notice 通知',
  'messageModal': 'Modal 弹框显示',
  'messageTooltip': 'Tooltip 文字提示',
  'messagePoptip': 'Poptip 自定义提示',
  'viewBadge': 'Badge 微标数',
  'viewCard': 'Card 卡片',
  'viewCollapse': 'Collapse 折叠面板',
  'viewTab': 'Tab 标签页',
  'viewTimeline': 'Timeline 时间轴',
  'viewBreadcrumb': 'Breadcrumb 面包屑',
  'otherAffix': 'Affix 图钉',
  'otherBacktop': 'BackTop 返回顶部',
  'guide': '入门',
  'quickstart': '快速上手',
  'themes': '样式替换',
  'logs': '日志',
  'home': '首页',
  'component': '组件',
  'resource': '资源',
  'about': '关于'
}


export default titles;
