<template>
  <div>
    <p>Selected value:{{select}}</p>
    <div v-width="300"><Select v-model="select" :datas="param" :filterable="true"></Select></div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      select: '',
      param: [
        '[United States] Honolulu',
        '[United States] Anchorage',
        '[Canada] Vancouver',
        '[United States] San Francisco',
        '[United States] Seattle',
        '[United States] Los Angeles',
        '[Canada] Aklavik',
        '[Canada] Edmonton',
        '[United States] Phoenix',
        '[United States] Denver',
        '[Mexico] Mexico City',
        '[Canada] Winnipeg',
        '[United States] Houston',
        '[United States] Minneapolis',
        '[United States] St.Paul',
        '[United States] New Orleans',
        '[United States] Chicago',
        '[United States] Montgomery',
        '[Guatemala] Guatemala',
        '[Salvador] San Salvador',
        '[Honduras] Tegucigalpa',
        '[Nicaragua] Managua',
        '[Cuba] Havana',
        '[United States] Indianapolis',
        '[United States] Atlanta',
        '[United States] Detroit',
        '[United States] Washington DC',
        '[United States] Philadelphia',
        '[Canada] Toronto',
        '[Canada] Ottawa',
        '[Bahamas] Nassau',
        '[Peru] Lima',
        '[Jamaica] Kingston',
        '[Cambodia] Bogota',
        '[United States] New York',
        '[Canada] Montreal',
        '[United States] Boston',
        '[Dominica] Santo Domingo',
        '[Bolivia] La Paz',
        '[Venezuela] Caracas',
        '[Puerto Rico] San Juan',
        '[Canada] Halifax',
        '[Chile] Santiago',
        '[Paraguay] Asuncion',
        "[Canada] St.John's",
        '[Argentina] Buenos Aires',
        '[Uruguay] Montevideo',
        '[Brazil] Brasilia',
        '[Brazil] Sao Paulo',
        '[Brazil] Rio de Janeiro',
        '[Iceland] Reykjavik',
        '[Portugal] Lisbon',
        '[Morocco] Casablanca',
        '[Ireland] Dublin',
        '[United Kingdom] London',
        '[Spain] Madrid',
        '[Spain] Barcelona',
        '[France] Paris',
        '[Nigeria] Lagos',
        '[Algeria] Algiers',
        '[Belgium] Brussels',
        '[Netherlands] Amsterdam',
        '[Switzerland] Geneva',
        '[Switzerland] Zurich',
        '[Germany] Frankfurt',
        '[Norway] Oslo',
        '[Denmark] Copenhagen',
        '[Italy] Rome',
        '[Germany] Berlin',
        '[Czech Republic] Prague',
        '[Croatia] Zagreb',
        '[Austria] Vienna',
        '[Sweden] Stockholm',
        '[Hungary] Budapest',
        '[Serbia and Montenegro] Belgrade',
        '[Poland] Warsaw',
        '[South Africa] Cape Town',
        '[Bulgaria] Sofia',
        '[Greece] Athens',
        '[Estonia] Tallinn',
        '[Finland] Helsinki',
        '[Romania] Bucharest',
        '[Belarus] Minsk',
        '[South Africa] Johannesburg'
      ]
    };
  }
};
</script>
