<template>
  <div>
    <p>Selected value: {{select}}</p>
    <div v-width="300"><Select v-model="select" :datas="param" :filterable="true" :multiple="true"></Select></div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      select: '',
      param: [
        'Honolulu',
        'Anchorage',
        'Vancouver',
        'San Francisco',
        'Seattle',
        'Los Angeles',
        'Aklavik',
        'Edmonton',
        'Phoenix',
        'Denver',
        'Mexico City',
        'Winnipeg',
        'Houston',
        'Minneapolis',
        'St.Paul',
        'New Orleans',
        'Chicago',
        'Montgomery',
        'Guatemala',
        'San Salvador',
        'Tegucigalpa',
        'Managua',
        'Havana',
        'Indianapolis',
        'Atlanta',
        'Detroit',
        'Washington DC',
        'Philadelphia',
        'Toronto',
        'Ottawa',
        'Nassau',
        'Lima',
        'Kingston',
        'Bogota',
        'New York',
        'Montreal',
        'Boston',
        'Santo Domingo',
        'La Paz',
        'Caracas',
        'San Juan',
        'Halifax',
        'Santiago',
        'Asuncion',
        "St.John's",
        'Buenos Aires',
        'Montevideo',
        'Brasilia',
        'Sao Paulo',
        'Rio de Janeiro',
        'Reykjavik',
        'Lisbon',
        'Casablanca',
        'Dublin',
        'London',
        'Madrid',
        'Barcelona',
        'Paris',
        'Lagos',
        'Algiers',
        'Brussels',
        'Amsterdam',
        'Geneva',
        'Zurich',
        'Frankfurt',
        'Oslo',
        'Copenhagen',
        'Rome',
        'Berlin',
        'Prague',
        'Zagreb',
        'Vienna',
        'Stockholm',
        'Budapest',
        'Belgrade',
        'Warsaw',
        'Cape Town',
        'Sofia',
        'Athens',
        'Tallinn',
        'Helsinki',
        'Bucharest',
        'Minsk',
        'Johannesburg'
      ]
    };
  }
};
</script>
