<template>
  <div>
    <p>选中值：{{select}}</p>
    <div v-width="300"><Select v-model="select" :datas="param" :filterable="true"></Select></div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      select: '',
      param: [
        '[美国] Honolulu 夏威夷檀香山',
        '[美国] Anchorage 阿拉斯加安克雷奇',
        '[加拿大] Vancouver 温哥华',
        '[美国] San Francisco 旧金山',
        '[美国] Seattle 西雅图',
        '[美国] Los Angeles 洛杉矶',
        '[加拿大] Aklavik 阿克拉维克',
        '[加拿大] Edmonton 艾德蒙顿',
        '[美国] Phoenix 凤凰城',
        '[美国] Denver 丹佛',
        '[墨西哥] Mexico City 墨西哥城',
        '[加拿大] Winnipeg 温尼伯',
        '[美国] Houston 休斯敦',
        '[美国] Minneapolis 明尼亚波利斯',
        '[美国] St.Paul 圣保罗',
        '[美国] New Orleans 新奥尔良',
        '[美国] Chicago 芝加哥',
        '[美国] Montgomery 蒙哥马利',
        '[危地马拉] Guatemala 危地马拉',
        '[萨尔瓦多] San Salvador 圣萨尔瓦多',
        '[洪都拉斯] Tegucigalpa 特古西加尔巴',
        '[尼加拉瓜] Managua 马那瓜',
        '[古巴] Havana 哈瓦那',
        '[美国] Indianapolis 印地安纳波利斯',
        '[美国] Atlanta 亚特兰大',
        '[美国] Detroit 底特律',
        '[美国] Washington DC 华盛顿哥伦比亚特区',
        '[美国] Philadelphia 费城',
        '[加拿大] Toronto 多伦多',
        '[加拿大] Ottawa 渥太华',
        '[巴哈马] Nassau 拿骚',
        '[秘鲁] Lima 利马',
        '[牙买加] Kingston 金斯敦',
        '[柬埔寨] Bogota 波哥大',
        '[美国] New York 纽约',
        '[加拿大] Montreal 蒙特利尔',
        '[美国] Boston 波士顿',
        '[多米尼加] Santo Domingo 圣多明各',
        '[玻利维亚] La Paz 拉帕兹',
        '[委内瑞拉] Caracas 加拉加斯',
        '[波多黎各] San Juan 圣胡安',
        '[加拿大] Halifax 哈里法克斯',
        '[智利] Santiago 圣地亚哥',
        '[巴拉圭] Asuncion 亚松森',
        '[加拿大] St.John\'s 圣约翰斯',
        '[阿根廷] Buenos Aires 布宜诺斯艾利斯',
        '[乌拉圭] Montevideo 蒙特维的亚',
        '[巴西] Brasilia 巴西利亚',
        '[巴西] Sao Paulo 圣保罗',
        '[巴西] Rio de Janeiro 里约热内卢',
        '[冰岛] Reykjavik 雷克雅未克',
        '[葡萄牙] Lisbon 里斯本',
        '[摩洛哥] Casablanca 卡萨布兰卡',
        '[爱尔兰] Dublin 都柏林',
        '[英国] London 伦敦',
        '[西班牙] Madrid 马德里',
        '[西班牙] Barcelona 巴塞罗那',
        '[法国] Paris 巴黎',
        '[尼日利亚] Lagos 拉各斯',
        '[阿尔及利亚] Algiers 阿尔及尔',
        '[比利时] Brussels 布鲁塞尔',
        '[荷兰] Amsterdam 阿姆斯特丹',
        '[瑞士] Geneva 日内瓦',
        '[瑞士] Zurich 苏黎世',
        '[德国] Frankfurt 法兰克福',
        '[挪威] Oslo 奥斯陆',
        '[丹麦] Copenhagen 哥本哈根',
        '[意大利] Rome 罗马',
        '[德国] Berlin 柏林',
        '[捷克] Prague 布拉格',
        '[克罗地亚] Zagreb 萨格雷布',
        '[奥地利] Vienna 维也纳',
        '[瑞典] Stockholm 斯德哥尔摩',
        '[匈牙利] Budapest 布达佩斯',
        '[塞尔维亚与蒙特内哥罗] Belgrade 贝尔格莱德',
        '[波兰] Warsaw 华沙',
        '[南非] Cape Town 开普敦',
        '[保加利亚] Sofia 索非亚',
        '[希腊] Athens 雅典城',
        '[爱沙尼亚] Tallinn 塔林',
        '[芬兰] Helsinki 赫尔辛基',
        '[罗马尼亚] Bucharest 布加勒斯特',
        '[白俄罗斯] Minsk 明斯克',
        '[南非] Johannesburg 约翰尼斯堡'
      ]
    };
  }
};
</script>
