module.exports = {
  'prefix': 'h-',
  'primary-color': '#45b984',
  'link-color': '#45b984',
  'blue-color': '#3B91FF',
  'green-color': '#13CE66',
  'yellow-color': '#FFAE00',
  'red-color': '#E11617',
  'white-color': '#ffffff',
  'dark-color': '#333333',
  'dark1-color': '#555555',
  'dark2-color': '#666666',
  'gray-color': '#999999',
  'gray1-color': '#d3d3d3',
  'gray2-color': '#eeeeee',
  'gray3-color': '#f3f3f3',
  'gray4-color': '#f9f9f9',
  'hover-background-color': 'rgba(51, 51, 51, 0.08)',
  'highlight-background-color': 'rgba(69, 185, 132, 0.15)',
  'tag-background-color': '#f5f5f5',
  'tag-border-color': '#ececec',
  'font-size': '14px',
  'font-size-mini': '13px',
  'font-size-input': '13px',
  'font-size-input-tag': '12px',
  'font-size-badge': '12px',
  'font-family': '"Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif',
  'line-height': '1.5',
  'line-height-computed': '21px',
  'button-size-normal-padding': '8px 15px',
  'button-size-l-padding': '10px 20px',
  'button-size-m-padding': '7px 16px',
  'button-size-s-padding': '5px 10px',
  'button-size-xs-padding': '2px 6px',
  'input-height': '30px',
  'border-color': '#eeeeee',
  'border': '1px solid #eeeeee',
  'disabled-cursor': 'not-allowed',
  'disabled-color': '#999999',
  'disabled-border-color': '#d3d3d3',
  'disabled-background-color': '#f9f9f9',
  'border-radius': '4px',
  'btn-border-radius': '4px',
  'box-shadow': '0 5px 10px rgba(0, 0, 0, 0.1)',
  'box-shadow-button': '0 1px 1px 0 #eeeeee',
  'box-shadow-notify': '0 5px 10px rgba(0, 0, 0, 0.1)',
  'box-shadow-dropdown': '0 5px 10px rgba(0, 0, 0, 0.1)',
  'box-shadow-select-dropdown': '0 1px 6px rgba(0, 0, 0, 0.2)',
  'switch-hight': '26px',
  'min-switch-height': '18px',
  'pop-ref-prefix': 'h-pop-trigger',
  'icon-prefix': 'h-icon-',
  'zindex-loading': '8',
  'zindex-affix': '10',
  'zindex-backtop': '10',
  'zindex-select': '1000',
  'zindex-dropdown': '1000',
  'zindex-modal': '1000',
  'zindex-notify': '1000',
  'zindex-notice': '1000',
  'zindex-message': '1010',
  'zindex-tooltip': '1060',
  'zindex-loading-fullscreen': '2000',
  'zindex-loading-bar': '2000',
  'animation-time': '0.3s',
  'transition-time': '0.2s',
  'panel-space': '10px',
  'layout-header-height': '64px',
  'layout-sider-width': '200px',
  'layout-sider-collapse-width': '70px',
  'menu-dark-color': '#333333',
  'menu-white-background-color': '#ecf8f2',
  'skeleton-bg': '#f2f2f2',
  'skeleton-height': '16px'
};
